---
# Deploy tools not found in the Kali repositories
# Install AutoRecon
- name: Ensure git is installed.
  apt:
    name: "git"
    state: present

- name: Copy AutoRecon from repository
  git:
    repo: https://github.com/Tib3rius/AutoRecon
    dest: /usr/share/autorecon
    update: yes
    force: yes

- name: Install AutoRecon Requirements
  pip:
    executable: pip3
    requirements: /usr/share/autorecon/requirements.txt

- name: Install pipx - Pt. 1
  ansible.builtin.shell: python3 -m pip install --user pipx
  become: true
  become_user: "{{user}}"
  args:
    executable: /bin/bash

- name: Install pipx - Pt. 2
  ansible.builtin.shell: python3 -m pipx ensurepath
  become: true
  become_user: "{{user}}"
  args:
    executable: /bin/bash

- name: Install pipx - Pt. 3
  ansible.builtin.shell: pipx install pipx
  become: true
  become_user: "{{user}}"
  args:
    executable: /bin/bash

- name: Resource bashrc
  ansible.builtin.shell: source /home/{{user}}/.bashrc
  become: true
  become_user: "{{user}}"
  args:
    executable: /bin/bash

- name: Install Autorecon via pipx - Root
  ansible.builtin.shell: /home/{{user}}/.local/bin/pipx install git+https://github.com/Tib3rius/AutoRecon.git

- name: Install AutoRecon via pipx - User
  become: true
  become_user: "{{user}}"
  ansible.builtin.shell: /home/{{user}}/.local/bin/pipx install git+https://github.com/Tib3rius/AutoRecon.git

# Install Sublime Text
- name: Install GPG key for SubLimeText
  ansible.builtin.apt_key:
    url: https://download.sublimetext.com/sublimehq-pub.gpg
    state: present

- name: Add Sublime repo into sources list using specified filename
  ansible.builtin.apt_repository:
    repo: deb https://download.sublimetext.com/ apt/stable/
    state: present
    filename: "sublime"

- name: Install Sublime package
  apt:
    state: latest
    pkg: "sublime-text"
    update_cache: yes

# Create the desired /usr/share/ file structure
- name: Create necessary directories
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  loop:
    - /usr/share/privsec/linux
    - /usr/share/privsec/windows
    - /usr/share/privsec/exploits
    - /usr/share/privsec/tools
    # - /usr/share/tools
    - /usr/share/tmp

# Clone git repos
- name: clone git repositories, download files and create directory structure
  block:
  - name: Clone git repositories
    
    ansible.builtin.git:
      repo: "{{ item.repo }}"
      dest: "/usr/share/tmp/{{ item.name }}"
      version: "{{ item.version | default('master') }}"
      depth: 1
      force: true
    loop: "{{ git_repos | flatten(levels=1) }}"
    ignore_errors: yes

  # Miscellaneous tools
  - name: Ensure destination directory exists
    ansible.builtin.file:
      dest: "{{ item.dest | dirname }}"
      state: directory
      owner: root
      group: root
      mode: 0755
    loop: "{{ misc_downloads }}"

  - name: Download files
    ansible.builtin.get_url:
      url: "{{ item.url }}"
      dest: "{{ item.dest }}"
      owner: root
      group: root
      mode: 0644
    loop: "{{ misc_downloads }}"
    ignore_errors: yes


  # Doing some directory copying to cure OCD
- name: file copies to cure OCD
  block:
  
    # - name: copy linpeas
    #   ansible.builtin.copy:
    #     src: /usr/share/tools/peas/linpeas.sh
    #     dest: /usr/share/privsec/linux/linpeas.sh

    # - name: copy winpeas
    #   ansible.builtin.copy:
    #     src: /usr/share/tools/peas/winpeas.exe
    #     dest: /usr/share/privsec/windows/winpeas.exe

    - name: copy autorecon
      ansible.builtin.copy:
        src: /usr/share/autorecon
        dest: /usr/share/privsec/

    - name: copy adpeas light
      ansible.builtin.copy:
        src: /usr/share/tmp/adpeas/adPEAS-Light.ps1
        dest: /usr/share/privsec/windows/adpeas_light.ps1
        
    - name: copy linenum
      ansible.builtin.copy:
        src: /usr/share/tmp/linenum/LinEnum.sh
        dest: /usr/share/privsec/linux/linenum.sh

    - name: copy jaws
      ansible.builtin.copy:
        src: /usr/share/tmp/just-another-windows-enum-script/jaws-enum.ps1
        dest: /usr/share/privsec/windows/jaws.ps1

    - name: copy linux-exploit-suggester-1
      ansible.builtin.copy:
        src: /usr/share/tmp/linux-exploit-suggester-1/linux-exploit-suggester.sh
        dest: /usr/share/privsec/linux/les.sh

    - name: copy linux-exploit-suggester-2
      ansible.builtin.copy:
        src: /usr/share/tmp/linux-exploit-suggester-2/linux-exploit-suggester-2.pl
        dest: /usr/share/privsec/linux/les2.pl

    - name: copy linux-smart-enumeration
      ansible.builtin.copy:
        src: /usr/share/tmp/linux-smart-enumeration/lse.sh
        dest: /usr/share/privsec/linux/lse.sh

    - name: copy droopescan
      ansible.builtin.copy:
        src: /usr/share/tmp/droopescan/
        dest: /usr/share/privsec/tools/droopescan/

    - name: copy joomscan
      ansible.builtin.copy:
        src: /usr/share/tmp/joomscan/
        dest: /usr/share/privsec/tools/joomscan/

    - name: copy gittools
      ansible.builtin.copy:
        src: /usr/share/tmp/gittools/
        dest: /usr/share/privsec/tools/gittools/

    - name: copy watson
      ansible.builtin.copy:
        src: /usr/share/tmp/watson/
        dest: /usr/share/privsec/tools/watson/

    # Unzip some archives
    - name: unzip nc
      ansible.builtin.unarchive:
        src: /usr/share/privsec/tools/nc/nc.zip
        dest: /usr/share/privsec/tools/nc/

    - name: unzip pstools
      ansible.builtin.unarchive:
        src: /usr/share/privsec/tools/pstools/pstools.zip
        dest: /usr/share/privsec/tools/pstools/

    # Delete the /usr/share/tmp directory 
    - name: deleting the /usr/share/tmp directory
      file:
        state: absent
        path: /usr/share/tmp/